# Generated by Django 4.0.5 on 2022-06-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.EmailField(max_length=254)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('identificador', models.CharField(max_length=10)),
                ('entregado', models.BooleanField(default=False)),
                ('peso', models.IntegerField()),
            ],
        ),
    ]
